/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./apps/web/index.html", "./apps/web/src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#584400",
        "on-surface": "#e3e2e5",
        "inverse-surface": "#e3e2e5",
        "tertiary-fixed-dim": "#bbc3ff",
        "primary-fixed": "#ffe08d",
        "outline-variant": "#4d4637",
        "surface-container": "#1f2022",
        "inverse-primary": "#745b00",
        "on-secondary-fixed-variant": "#484740",
        "secondary-fixed": "#e6e2d8",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#38427e",
        "surface-container-highest": "#343537",
        "on-background": "#e3e2e5",
        "on-error": "#690005",
        error: "#ffb4ab",
        "on-tertiary": "#202b66",
        "on-primary-fixed": "#241a00",
        "surface-dim": "#121315",
        "surface-variant": "#343537",
        "secondary-fixed-dim": "#cac6bd",
        "on-primary-container": "#5c4800",
        "on-tertiary-container": "#3b4681",
        "secondary-container": "#484740",
        tertiary: "#ced3ff",
        "tertiary-container": "#acb6fa",
        "on-surface-variant": "#d0c5b2",
        "primary-fixed-dim": "#e5c365",
        "tertiary-fixed": "#dee0ff",
        "surface-container-high": "#292a2c",
        "surface-tint": "#e5c365",
        "surface-container-low": "#1b1c1e",
        "surface-bright": "#38393b",
        "on-secondary-fixed": "#1c1c16",
        secondary: "#cac6bd",
        "surface-container-lowest": "#0d0e10",
        background: "#121315",
        "primary-container": "#d8b75a",
        "on-secondary-container": "#b8b5ac",
        "on-secondary": "#31312a",
        "inverse-on-surface": "#303033",
        primary: "#f6d372",
        "on-primary": "#3d2f00",
        surface: "#121315",
        "on-tertiary-fixed": "#081450",
        "on-error-container": "#ffdad6",
        outline: "#98907e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-gap": "1px",
        "container-padding": "24px",
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "16px",
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "mono-data": ["Geist Mono", "monospace"],
        "mono-label": ["Geist Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-label": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
